const REGIONS = [
  // ---------------- IITs ----------------
  { value: "iit-bombay", label: "IIT Bombay" },
  { value: "iit-delhi", label: "IIT Delhi" },
  { value: "iit-madras", label: "IIT Madras" },
  { value: "iit-kanpur", label: "IIT Kanpur" },
  { value: "iit-kharagpur", label: "IIT Kharagpur" },
  { value: "iit-roorkee", label: "IIT Roorkee" },
  { value: "iit-guwahati", label: "IIT Guwahati" },
  { value: "iit-hyderabad", label: "IIT Hyderabad" },
  { value: "iit-indore", label: "IIT Indore" },
  { value: "iit-bhu", label: "IIT BHU Varanasi" },
  { value: "iit-patna", label: "IIT Patna" },
  { value: "iit-ropar", label: "IIT Ropar" },
  { value: "iit-mandi", label: "IIT Mandi" },
  { value: "iit-gandhinagar", label: "IIT Gandhinagar" },
  { value: "iit-jodhpur", label: "IIT Jodhpur" },
  { value: "iit-bhubaneswar", label: "IIT Bhubaneswar" },
  { value: "iit-goa", label: "IIT Goa" },
  { value: "iit-dharwad", label: "IIT Dharwad" },
  { value: "iit-jammu", label: "IIT Jammu" },
  { value: "iit-tirupati", label: "IIT Tirupati" },
  { value: "iit-palakkad", label: "IIT Palakkad" },
  { value: "iit-bhilai", label: "IIT Bhilai" },
  { value: "iit-dhanbad", label: "IIT Dhanbad (ISM)" },

  // ---------------- NITs ----------------
  { value: "nit-trichy", label: "NIT Trichy" },
  { value: "nit-surathkal", label: "NIT Surathkal" },
  { value: "nit-warangal", label: "NIT Warangal" },
  { value: "nit-calicut", label: "NIT Calicut" },
  { value: "nit-rourkela", label: "NIT Rourkela" },
  { value: "nit-allahabad", label: "NIT Allahabad (MNNIT)" },
  { value: "nit-nagpur", label: "NIT Nagpur (VNIT)" },
  { value: "nit-jaipur", label: "NIT Jaipur (MNIT)" },
  { value: "nit-bhopal", label: "NIT Bhopal (MANIT)" },
  { value: "nit-durgapur", label: "NIT Durgapur" },
  { value: "nit-jamshedpur", label: "NIT Jamshedpur" },
  { value: "nit-patna", label: "NIT Patna" },
  { value: "nit-kurukshetra", label: "NIT Kurukshetra" },
  { value: "nit-silchar", label: "NIT Silchar" },
  { value: "nit-hamirpur", label: "NIT Hamirpur" },
  { value: "nit-srinagar", label: "NIT Srinagar" },
  { value: "nit-raipur", label: "NIT Raipur" },
  { value: "nit-agartala", label: "NIT Agartala" },
  { value: "nit-arunachal", label: "NIT Arunachal Pradesh" },
  { value: "nit-delhi", label: "NIT Delhi" },
  { value: "nit-goa", label: "NIT Goa" },
  { value: "nit-manipur", label: "NIT Manipur" },
  { value: "nit-meghalaya", label: "NIT Meghalaya" },
  { value: "nit-mizoram", label: "NIT Mizoram" },
  { value: "nit-nagaland", label: "NIT Nagaland" },
  { value: "nit-puducherry", label: "NIT Puducherry" },
  { value: "nit-sikkim", label: "NIT Sikkim" },
  { value: "nit-uttarakhand", label: "NIT Uttarakhand" },

  // ---------------- IIITs (Top Ones) ----------------
  { value: "iiit-hyderabad", label: "IIIT Hyderabad" },
  { value: "iiit-bangalore", label: "IIIT Bangalore" },
  { value: "iiit-delhi", label: "IIIT Delhi" },
  { value: "iiit-allahabad", label: "IIIT Allahabad" },
  { value: "iiit-gwalior", label: "IIIT Gwalior" },
  { value: "iiit-jabalpur", label: "IIIT Jabalpur" },

  // ---------------- Other Top Institutes ----------------
  { value: "bits-pilani", label: "BITS Pilani" },
  { value: "bits-goa", label: "BITS Goa" },
  { value: "bits-hyderabad", label: "BITS Hyderabad" },
  { value: "iis-bangalore", label: "IISc Bangalore" },
  { value: "jadavpur", label: "Jadavpur University" },
  { value: "anna-university", label: "Anna University" },
  { value: "vit-vellore", label: "VIT Vellore" },
  { value: "srm", label: "SRM University" },

  // ---------------- Default ----------------
  { value: "other", label: "Other" },
];

export default REGIONS;
